LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

TARGET_PLATFORM := android-9

LOCAL_MODULE := lighttpd
LOCAL_SRC_FILES := \
../src/array.c \
../src/bitset.c \
../src/buffer.c \
../src/chunk.c \
../src/configfile-glue.c \
../src/configfile.c \
../src/configparser.c \
../src/connections-glue.c \
../src/connections.c \
../src/crc32.c \
../src/data_array.c \
../src/data_config.c \
../src/data_count.c \
../src/data_fastcgi.c \
../src/data_integer.c \
../src/data_string.c \
../src/etag.c \
../src/fdevent.c \
../src/fdevent_freebsd_kqueue.c \
../src/fdevent_libev.c \
../src/fdevent_linux_sysepoll.c \
../src/fdevent_poll.c \
../src/fdevent_select.c \
../src/fdevent_solaris_devpoll.c \
../src/fdevent_solaris_port.c \
../src/http-header-glue.c \
../src/http_auth.c \
../src/http_chunk.c \
../src/inet_ntop_cache.c \
../src/joblist.c \
../src/keyvalue.c \
../src/lemon.c \
../src/lempar.c \
../src/lighttpd-angel.c \
../src/log.c \
../src/md5.c \
../src/mod_access.c \
../src/mod_accesslog.c \
../src/mod_alias.c \
../src/mod_auth.c \
../src/mod_cgi.c \
../src/mod_cml.c \
../src/mod_cml_funcs.c \
../src/mod_cml_lua.c \
../src/mod_compress.c \
../src/mod_dirlisting.c \
../src/mod_evasive.c \
../src/mod_evhost.c \
../src/mod_expire.c \
../src/mod_extforward.c \
../src/mod_fastcgi.c \
../src/mod_flv_streaming.c \
../src/mod_indexfile.c \
../src/mod_magnet.c \
../src/mod_magnet_cache.c \
../src/mod_mysql_vhost.c \
../src/mod_proxy.c \
../src/mod_redirect.c \
../src/mod_rewrite.c \
../src/mod_rrdtool.c \
../src/mod_scgi.c \
../src/mod_secure_download.c \
../src/mod_setenv.c \
../src/mod_simple_vhost.c \
../src/mod_skeleton.c \
../src/mod_ssi.c \
../src/mod_ssi_expr.c \
../src/mod_ssi_exprparser.c \
../src/mod_staticfile.c \
../src/mod_status.c \
../src/mod_trigger_b4_dl.c \
../src/mod_userdir.c \
../src/mod_usertrack.c \
../src/mod_webdav.c \
../src/network.c \
../src/network_freebsd_sendfile.c \
../src/network_linux_sendfile.c \
../src/network_openssl.c \
../src/network_solaris_sendfilev.c \
../src/network_write.c \
../src/network_writev.c \
../src/plugin.c \
../src/proc_open.c \
../src/request.c \
../src/response.c \
../src/server.c \
../src/splaytree.c \
../src/stat_cache.c \
../src/status_counter.c \
../src/stream.c

include $(BUILD_EXECUTABLE)
